import "@styles/global.css";

import Footer from "@components/ui/footer";
import GlobalNav from "@components/ui/global-nav";
import { Raleway } from "next/font/google";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import type { ReactNode } from "react";
import { Providers } from "./provider";

const raleway = Raleway({ subsets: ["latin"] });

export const metadata = {
  title: "Next15 TypeScript Template",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="ko">
      <body className={raleway.className}>
        <NuqsAdapter>
          <Providers>
            <GlobalNav />
            {children}
            <Footer />
          </Providers>
        </NuqsAdapter>
      </body>
    </html>
  );
}
