import "@styles/global.css";

import Footer from "@components/ui/footer";
import GlobalNav from "@components/ui/global-nav";
import type { ReactNode } from "react";
import { Providers } from "./provider";

export const metadata = {
  title: "Next.js 16 Fullstack Template",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="ko" className="h-full">
      <body className="flex min-h-full flex-col bg-white antialiased">
        <Providers>
          <div className="fixed inset-0 -z-10 h-full w-full bg-white bg-grid-slate-100 [mask-image:linear-gradient(to_bottom,white,transparent)]" />
          <GlobalNav />
          <div className="flex-1">{children}</div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
